DROP TABLE IF EXISTS contacts CASCADE;
DROP TABLE IF EXISTS groups CASCADE;

create table groups
(
    group_id          bigint generated by default as identity
        primary key,
    group_name        varchar,
    group_description varchar(2000) not null,
    group_category    varchar       not null,
    create_date       timestamp
);

create table contacts
(
    contact_id       bigint generated by default as identity
        primary key,
    contact_name     varchar,
    group_id         bigint  not null
        references groups,
    contact_company  varchar not null,
    contact_email    varchar not null
        unique,
    contact_religion varchar not null
);

